### ISSUE TITLE
Add a Boolean version

### ISSUE THREAD

**Issue by coreman14** [whtsky/pixelmatch-py#143]
I was wondering if adding a boolean version of the pixelmatch method would be a good idea.

For my current project, due to the images being the same but in different formats/variations, pixel match has been really good at helping me sus out matching. But when all I'm looking for is a zero, the extra time it takes isn't needed.

So if a method was added that would do the exact same thing but, instead of adding one to a counter, just returned false right away.

```python
from PIL import Image

from pixelmatch.contrib.PIL import dopixelsmatch

img_a = Image.open("a.png")
img_b = Image.open("b.png")

if dopixelsmatch(img_a, img_b):
    #Do something
```

**Comment by whtsky** [comment]
`pixelmatch` returns the number of mismatched pixels. And `0` is a Falsy value in Python, I assume `if pixelmatch(img_a, img_b)` should just works.

**Comment by coreman14** [comment]
While true, I'm looking at timing rather than if it would work with `==` or `!=`

When I'm using it, a match doesn't take that long. But when a bad image comes up, ~5000 to ~6000 pixels, it can take about **30 seconds** or so.

Sometimes, I don't need the exact number of bad pixels. So if there was a method that acted the same as what it has now, but when it finally finds a different pixel and returns false/1, it could greatly speed up what I'm doing.

**Comment by whtsky** [comment]
Thanks for clarify.
Adding a new method for this might involve a lot of copy/pasted code and increased maintenance cost.
Maybe we can add a `failfast: bool = False` parameter in pixelmatch to return 1 when encountered first bad pixel.

Feel free to submit a PR for this 😄

**Comment by coreman14** [comment]
Opened PR #144
