### ISSUE TITLE
support for pixelmatching directly on PIL.Image objects

### ISSUE THREAD

**Issue by Mattwmaster58** [whtsky/pixelmatch-py#36]
I can see that this project has no dependencies currently, and this would add Pillow. But chances are people will already be using Pillow to manipulate their image data, so I think the impact would be minimal.

I would be willing to write a PR that implements this.

**Comment by whtsky** [comment]
> But chances are people will already be using Pillow to manipulate their image data

In fact, I’m using matplotlib 😄

I’d be happy if you contribute a helper function to deal with Pillow data. Pillow doesn’t need to be a dependency, we can raise an ImportError when user calls the function without Pillow installed.
