### ISSUE TITLE
OpenCV image support

### ISSUE THREAD

**Issue by detrin** [whtsky/pixelmatch-py#80]
This library supports only PIL type of image. It would be nice to add OpenCV support so that the main input function would take as input NumPy arrays. Also, it seems like the width and the height of images could be determined inside the package rather than outside. I would be willing to write PR, but it won't be sooner than in three weeks

**Comment by whtsky** [comment]
I'm not familiar with OpenCV, and any PR is welcomed.

>  the width and the height of images could be determined inside the package rather than outside

They can't be determined with [Raw Image Data Comparison](https://github.com/whtsky/pixelmatch-py/blob/2bf4eb52733914ca1fb9b65cadbc0b0a76ae0994/README.md#raw-image-data-comparison), but IMO it's doable in OpenCV support.

**Comment by detrin** [comment]
This is no longer issue for me.
